### ISSUE TITLE
Section of preliminaries.ipynb fails with error

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/Polar_Binning_DeltaG#28]
When I get to the "Boilerplate read and parse the files" section pandas throws an error after trying to run read_rep. I have tracked this down to duplicate code that overwrites the variables (see image below). Deleting these lines appears to fix the issue.
![read_rep](https://github.com/BranniganLab/Polar_Binning_DeltaG/assets/22152851/ce390044-a89f-4752-8bb6-7f01eca10a6d)

**Comment by JesseSandberg** [comment]
setting the index to 2 in line 421 causes pandas to look for "avg" as a key instead of something it knows ("upp")

**Comment by EzryStIago** [comment]
See PR28

**Comment by JesseSandberg** [comment]
This was fixed by latest PR
