### ISSUE TITLE
relative paths in config force user to run TCL from within repo directory

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/Polar_Binning_DeltaG#30]
Some may prefer (me included) to run from a separate directory. I implemented a fix for this on the old branch that we can review at some point.

**Comment by gbrannigan** [comment]
@JesseSandberg Isn't this up to the user? Why do we need a fix? I need more details; otherwise it seems that the user can choose to use relative paths or not in their own config file.

**Comment by JesseSandberg** [comment]
Oh wow. Yes it is. We do not need a fix. Sorry!
