### ISSUE TITLE
gpcr sample config has ELIC helix assigner script in it

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/Polar_Binning_DeltaG#31]
need to switch ELIC to GPCR on helix_assignment_script line

**Comment by gbrannigan** [comment]
Also a bug in the Master branch, fixed by [26e6881](https://github.com/BranniganLab/Polar_Binning_DeltaG/commit/26e6881014fa9f441ff05e8049d0d5da015cc66f)

**Comment by JesseSandberg** [comment]
@gbrannigan you fixed this on master but not on TCL-cleanup. Wouldn't your fix on master get wiped unless you pull master into TCL-cleanup?

**Comment by gbrannigan** [comment]
@JesseSandberg Incorporated into Issue #40
