### ISSUE TITLE
TCL-cleanup: USE_QWRAP is not a global variable

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/Polar_Binning_DeltaG#34]
center_system can't access USE_QWRAP in order to work

**Comment by gbrannigan** [comment]
It should not be a global variable; is now passed as an argument to center_and_wrap_system. Closed with [8caa892](https://github.com/BranniganLab/Polar_Binning_DeltaG/commit/8caa89257acc63b845f9139a4d20b4936b337e9d)
