### ISSUE TITLE
TCL-cleanup: polarDensityBin crashes after starting binning

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/Polar_Binning_DeltaG#35]
error message: "can't read "start": no such variable"

also: "can't read "end": no such variable"

**Comment by JesseSandberg** [comment]
first error ("start") is fixed by changing "start" to "start_frame" on line 540

**Comment by JesseSandberg** [comment]
second error is not fixed (!) by changing "end" to "end_frame" on lines 505, 509, and 540.

**Comment by gbrannigan** [comment]
Fixed with [8caa892](https://github.com/BranniganLab/Polar_Binning_DeltaG/commit/8caa89257acc63b845f9139a4d20b4936b337e9d)
