### ISSUE TITLE
TCL-cleanup: Leaflet reassignment reports an incorrect number

### ISSUE THREAD

**Issue by EzryStIago** [BranniganLab/Polar_Binning_DeltaG#37]
When leaflet_reassign_t is 1, I get “Checked for leaflet reassignment 1 times.” 
Shouldn't it be checked 10 times for a 10-frame trajectory?

**Comment by gbrannigan** [comment]
@EzryStIago I cannot reproduce, please provide MWE

**Comment by gbrannigan** [comment]
@EzryStIago In this case the leaflet assignment was correct but the script was executing before you had loaded all the frames.  Fix [d92afde](https://github.com/BranniganLab/Polar_Binning_DeltaG/pull/27/commits/d92afde9693289e3c5e5c538b679445fb7a4ef6e) would make this more obvious
