### ISSUE TITLE
TCL-cleanup: no default parameter set for leaflet_reassign_interval

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/Polar_Binning_DeltaG#42]
can't read "leaflet_reassign_interval": no such variable

**Comment by JesseSandberg** [comment]
This was fixed by changing the variable name in the config file I was using

**Comment by gbrannigan** [comment]
To clarify the issue:  If the user doesn't assign leaflet_reassign_interval in the config file, no default value is set.
